### ISSUE TITLE
Ensure COMPUTE_SETTINGS_VARNAME is set in just one location

### ISSUE THREAD

**Issue by vreuter** [pepkit/divvy#23]

**Comment by nsheff** [comment]
what is this issue actually saying?

**Comment by nsheff** [comment]
@stolarczyk I think in the past we had `COMPUTE_SETTINGS_VARNAME` both in divvy and in peppy. Now on dev I don't see it anywhere except divvy so I think we can close this issue. just wanted to double-check with you.

**Comment by stolarczyk** [comment]
yes, I peppy is not aware of the compute settings and looper uses `select_divvy_config` function from divvy which uses the `COMPUTE_SETTINGS_VARNAME` set there.
