### ISSUE TITLE
streamline utils

### ISSUE THREAD

**Issue by nsheff** [pepkit/divvy#25]
I notice `divvy` has stuff like `check_bam` in the `utils.py` file.

Is this for a reason or just duplicated from another source? Do we need to create a utils package to depend on?

**Comment by vreuter** [comment]
Yes, it feels like enough times now that a scenario with value has come up.

**Comment by vreuter** [comment]
https://github.com/pepkit/ubiquerg

**Comment by nsheff** [comment]
hey, this is where ubiquerg came from.

**Comment by vreuter** [comment]
Yep, should we close, or leave open as a sort of occasional subtle reminder to consider sharing helpers?

**Comment by nsheff** [comment]
fine to close.
