### ISSUE TITLE
How to handle on-the-fly command line variables

### ISSUE THREAD

**Issue by nsheff** [pepkit/divvy#50]
Right now any unknown args are just taken by divvy to populate template variables.

Should we instead use the `--compute` idea from looper so that you have to say:

`--compute key=value,key2=val2` ?

Pros: explicit what's happening
Cons: more verbose

**Comment by nsheff** [comment]
@stolarczyk what do you think? Just wondering if it makes sense to keep consistent with looper... or if for divvy we value the simplicity more

**Comment by stolarczyk** [comment]
I like the explicit approach more, but that's just slight preference

**Comment by nsheff** [comment]
follow-up question: why is it:

`--compute k1=v1,k2=v2`

instead of `--compute k1=v1 k2=v2`.

With the latter we could use the nargs="+" type and let argparser do the parsing; with the former we're having to parse it separately, within looper, right? is there a reason to do it that way?

**Comment by stolarczyk** [comment]
that's right, this is how it's done now. I just followed the way it was implemented. The new way would spare splitting by comma part, that's nice. Not sure if there is any reason to do it this way. I'll try to make it use argparser parsing. We could also set the metavar in the parser instead of putting it to the help:

```python
parser.add_argument("--compute",
                        metavar="KEY=VALUE",
                        nargs='+', ...
```

**Comment by nsheff** [comment]
this is working for me now; try with:

```
divvy submit -p local -c code=ls
```

```
divvy write -p local -c code=ls
```
