### ISSUE TITLE
why pandas is a dependency?

### ISSUE THREAD

**Issue by leoank** [pepkit/divvy#59]
`pandas` is mentioned as a dependency in `requirements/requirements-all.txt` file.

I am unable to find any usage of pandas in the source code.
I guess, it can be removed from the dependencies.
Let me know if it is true, I'll send a PR with the fix.

**Comment by stolarczyk** [comment]
you're right, pandas should not be a dependency. 

> I'll send a PR with the fix.

please do!

**Comment by leoank** [comment]
here you go!
