### ISSUE TITLE
divvy inspect

### ISSUE THREAD

**Issue by nsheff** [pepkit/divvy#62]
`divvy inspect <package>` would be nice

**Comment by ayobi** [comment]
Are we wanting to inspect the active compute package @nsheff? Where we can see the current activated compute package or some other package that divvy handles?

**Comment by nsheff** [comment]
you'd specify which package to inspect. with divvy, there isn't really a concept of an "active" compute package, you supply it with the `<package>` argument to `divvy write`, etc.

**Comment by ayobi** [comment]
Ok, I have it working to inspect all the packages, using `divvy inspect -p slurm`

We get:
`Your compute package template for: slurm

#!/bin/bash
#SBATCH --job-name='{JOBNAME}'
#SBATCH --output='{LOGFILE}'
#SBATCH --mem='{MEM}'
#SBATCH --cpus-per-task='{CORES}'
#SBATCH --time='{TIME}'
#SBATCH --partition='{PARTITION}'
#SBATCH -m block
#SBATCH --ntasks=1

echo 'Compute node:' `hostname`
echo 'Start time:' `date +'%Y-%m-%d %T'`

{CODE}`

If package isn't found `divvy inspect -p uhh` we get:

`Your compute package template for: uhh

Package not found. Use 'divvy list' to see list of packages.`

**Comment by ayobi** [comment]
I tried adding Singularity args but it was giving me attribute errors, I thought may it was because in the divvy config has just quotes: `singularity_args: ""`
