### ISSUE TITLE
Remove attmap dependency

### ISSUE THREAD

**Issue by nsheff** [pepkit/divvy#63]
I think it might make sense for you to tackle this since it's fresh in your mind, @vreuter

**Comment by ayobi** [comment]
Some notes and a question: In looper, vince mentioned he removed ‘direct’ attmap dependency like `from attmap import AttMap`

With divvy, there were no direct dependencies like this, just extensions like ‘yacman.YacAttMap()’ which all can be changed to ‘yacman.YAMLConfigManager()’ throughout divvy no problem https://github.com/pepkit/looper/commit/cc89ae972de07283c8bb81ce44e7d33f27b3fae6 except for the main call ‘class ComputingConfiguration(yacman.YacAttMap)’. One of the reasons is divvy uses the extensions like `class add_entries` from `_att_map_like` in `attmap` that is from `YacAttMap()`.

When changing to `class ComputingConfiguation(yacman.YAMLConfigManager), outside of missing `add_entries`, the program calls things differently: adapter, compute_packages, and compute are made after self in `yacman.YacAttMap()`, but with `yamlConfigManager` it’s self, then data, then you have those available. I haven’t look a lot into the why for that yet though but I'm just noting that change in behavior.

Just wondering, are we looking just to not directly depend on `attmap` and use it when needed via yacman? Or are we trying to fully turn away from `attmap` directly first, then try to fully transition from `yacman`, an extension of attmap, into `yacman1`, where we will fully rely on `YAMLConfigManager`?

**Comment by nsheff** [comment]
> Just wondering, are we looking just to not directly depend on `attmap` and use it when needed via yacman? Or are we trying to fully turn away from `attmap` directly first, then try to fully transition from `yacman`, an extension of attmap, into `yacman1`, where we will fully rely on `YAMLConfigManager`?

You can find the motivation and history here: https://github.com/databio/yacman/issues/58

**Comment by donaldcampbelljr** [comment]
I believe this issue has been solved with the integration of divvy into Looper and the removal of attmap within Looper.
